### PR TITLE
Add py37 to tox.ini

### PR DESCRIPTION
**Pull request by hairychris**

### CODE REVIEW

**Comment by carver** [comment]
From the travis issue:
> So for now the best thing to do is to have `sudo: required` just for job with 3.7.0.

Maybe this workaround could get us there without waiting ^ ?

**Comment by carver** [comment]
> this is not blocking anything ... the only thing missing is linux wheels for 3.7

Cool, is there anything blocking the release of the linux wheels?

---

@hairychris The Travis thread implies that `dist: xenial` might also be required

**Comment by carver** [comment]
Thanks wbolster!

@hairychris ah, and now 3.4 is busted, which people in that thread experienced too. That's why the final line was (my emphasis):
> So for now the best thing to do is to have `sudo: required` **just** for job with 3.7.0.

**Comment by hairychris** [comment]
Yeah I thought that might happen but worth checking, I don't really want to change too much to get around a temporary issue.

**Comment by wbolster** [comment]
i published plyvel 1.0.5 with python 3.7 wheels on pypi. https://plyvel.readthedocs.io/en/latest/news.html

**Comment by wbolster** [comment]
i pushed the `tox.ini` changes in fbfaecdd07126fa7a113a96b6c27ac7099510b42

let's wait for travis to settle before introducing hacks that will quickly turn into technical debt when travis sorts out their infra.

**Comment by wbolster** [comment]
for those interested: 20d1d2c2ffb43774d415d92d9f80726fb1d5859d  contains the build changes i referred to earlier

**Comment by wbolster** [comment]
closing, see #102

**Pull request closed without merging**
